services:
  meilisearch:
    image: getmeili/meilisearch:v1.10
    container_name: meilisearch
    restart: unless-stopped
    environment:
      - MEILI_ENV=development
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=stpsearchkey
    ports:
      - "7700:7700"
    volumes:
      - ./meili_data:/meili_data
